version: "3"

services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:fpm
    volumes:
      - ./:/app